### ISSUE TITLE
bootLogsActivity method never called

### ISSUE THREAD

**Issue by Rtransat** [spatie/activitylog#16]
Hi,

I use Log model events, so I've implemented the interface in my User model and add the trait, but the ```bootLogsActivity``` method is never called. So I've tried the code below in my model:

```php
protected static function boot()
{
	self::bootLogsActivity();
}

public function getActivityDescriptionForEvent($eventName)
{
	dd($eventName);
	if($eventName == 'updated')
	{
		return trans('activity.user.updated', ['name' => $this->profile->present()->fullName]);
	}

	return '';
}
```

The die and dump is never called. What's wrong in my case ?

**Comment by Rtransat** [comment]
In Model class I saw boot method start the bootXXX method :)

The problem is, the ```updated``` event is never called in my case :/. ```created``` and ```deleted``` works but ```updated``` don't.

**Comment by freekmurze** [comment]
What are you doing to trigger an update? Are you changing a field on your model?

**Comment by Rtransat** [comment]
I use update method, User::update

**Comment by freekmurze** [comment]
And are you updating any values on the model? Laravel is smart enough not to send the update event when no values have changed.

**Comment by freekmurze** [comment]
I'm assuming that you never updated a value on your model, and that's why update wasn't called. If I'm wrong, reopen this issue.
