### ISSUE TITLE
Logging Old and New Values on Update

### ISSUE THREAD

**Issue by codydh** [spatie/activitylog#21]
I'm trying to implement logging on a model of mine. Namely, when a value is updated, I'd like to log what the previous value was, and what the new value is. Is there a straightforward way to do this using ActivityLog?

**Comment by sebastiandedeyne** [comment]
You'd have to manually bind an event to `updating`. Quick example:

```php
protected static function boot()
{
    static::updating(function ($model) {
        Activity::log("{$model->name} just updated to {$model->getOriginal('name')}");
    }
}
```
