### ISSUE TITLE
How to add more fields like content_type & content_id?

### ISSUE THREAD

**Issue by webmastervinay** [spatie/activitylog#22]
Hello, Thanks for the wonderful script. Just one doubt. How can we add more fields like content_type & id so that we can fetch records based on content_type. Thanks in advance.

**Comment by freekmurze** [comment]
Hi, currently using your own model is not possible. We plan to add this is a future major version of the package. No ETA on that though.

**Comment by Cannonb4ll** [comment]
+1 on this feature

**Comment by BojanKogoj** [comment]
+1, polymorphic relations needed a lot!

**Comment by freekmurze** [comment]
We well add this in the next major release of te package. ETA: first half of 2016. If you need this quicker, feel free to submit a PR.
