### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by XavRsl** [spatie/activitylog#23]
Hi,
The path to Guard changed in Laravel 5.2 from ```Illuminate\Auth\Guard;```to ```Illuminate\Contracts\Auth\Guard;```. This will need to be updated in ActivitylogSupervisor.php

Thanks,

Xavier

**Comment by arcanedev-maroc** [comment]
Hi @XavRsl, 

This change means that you're going to use an abstract class than a concrete one.

**Comment by XavRsl** [comment]
The change is to be made in the package if you don't want an error to be thrown. I just saw that after updating to 5.2.

**Comment by arcanedev-maroc** [comment]
It's a good change, because its decouple the code from the dependency and we can extend the Guard with a custom one.

**Comment by XavRsl** [comment]
Yep !

**Comment by kaptanblack** [comment]
Hi,

Guard problem fixed for laravel 5.2

https://github.com/spatie/activitylog/pull/24

**Comment by spilxx** [comment]
Hi,

I have this problem:

FatalErrorException in Model.php line 852:
Class name must be a valid object or a string

The problem is at the model, relationship:

return $this->belongsTo(Config::get('auth.model'), 'user_id');

Thanks!

**Comment by spilxx** [comment]
I found the solution:

in 'public function user()' change: 

return $this->belongsTo(Config::get('auth.model'), 'user_id');

        return $this->belongsTo(Config::get('auth.providers.users.model'), 'user_id');

**Comment by freekmurze** [comment]
Version 2.3.0 of the package is compatible with L5.2
Thanks for your help!
