### ISSUE TITLE
Foreign key

### ISSUE THREAD

**Issue by vadimsg** [spatie/activitylog#25]
Can you please add possibility to change primary key from user_id to any other in config?

**Comment by freekmurze** [comment]
I'm not sure want you want. user_id isn't the primary key.

**Comment by vadimsg** [comment]
wup sorry, kinda misspelled. I meant foreign key. I need to replace it to admin_id.

**Comment by freekmurze** [comment]
Currently this is not possible, but I'd accept a PR that adds this (reading the foreign key name from the config file) to the package.
