### ISSUE TITLE
BadMethodCallException

### ISSUE THREAD

**Issue by pongz79** [spatie/activitylog#27]
Hi,

I'm trying to use this package with Laravel 5.1 and I'm getting the error that's on the title.
I've followed all the installation steps successfully but when I try to call the simple example that's on manual logging I'm getting this error.

BadMethodCallException thrown with message "Call to undefined method Illuminate\Database\Query\Builder::log()"

Stacktrace:
#68 BadMethodCallException in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php:2099
#67 Illuminate\Database\Query\Builder:__call in [internal]:0
#66 Illuminate\Database\Query\Builder:log in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:949
#65 call_user_func_array in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Builder.php:949
#64 Illuminate\Database\Eloquent\Builder:__call in [internal]:0
#63 Illuminate\Database\Eloquent\Builder:log in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:3499
#62 call_user_func_array in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:3499
#61 Illuminate\Database\Eloquent\Model:__call in [internal]:0
#60 Spatie\Activitylog\Models\Activity:log in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:3513
#59 call_user_func_array in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php:3513
#58 Illuminate\Database\Eloquent\Model:__callStatic in /var/www/html/eo-wallet/app/Http/Models/v1/Bet365/Balance.php:52
#57 Spatie\Activitylog\Models\Activity:log in /var/www/html/eo-wallet/app/Http/Models/v1/Bet365/Balance.php:52
#56 App\Http\Models\v1\Bet365\Balance:getBalance in /var/www/html/eo-wallet/app/Http/Models/v1/Wallet.php:48
#55 App\Http\Models\v1\Wallet:getBalance in /var/www/html/eo-wallet/app/Http/Controllers/v1/BalanceController.php:92
#54 App\Http\Controllers\v1\BalanceController:getBalance in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:256
#53 call_user_func_array in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Routing/Controller.php:256
#52 Illuminate\Routing\Controller:callAction in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:164
#51 Illuminate\Routing\ControllerDispatcher:call in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:112
#50 Illuminate\Routing\ControllerDispatcher:Illuminate\Routing\{closure} in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139
#49 call_user_func in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139
#48 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
#47 call_user_func in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
#46 Illuminate\Pipeline\Pipeline:then in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:114
#45 Illuminate\Routing\ControllerDispatcher:callWithinStack in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php:69
#44 Illuminate\Routing\ControllerDispatcher:dispatch in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Routing/Route.php:203
#43 Illuminate\Routing\Route:runWithCustomDispatcher in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Routing/Route.php:134
#42 Illuminate\Routing\Route:run in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Routing/Router.php:708
#41 Illuminate\Routing\Router:Illuminate\Routing\{closure} in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139
#40 call_user_func in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139
#39 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/eo-wallet/app/Http/Middleware/v1/WalletUserAuth.php:67
#38 App\Http\Middleware\v1\WalletUserAuth:handle in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#37 call_user_func_array in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#36 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/eo-wallet/app/Http/Middleware/v1/GetBalanceParametersValidator.php:56
#35 App\Http\Middleware\v1\GetBalanceParametersValidator:handle in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#34 call_user_func_array in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#33 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
#32 call_user_func in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
#31 Illuminate\Pipeline\Pipeline:then in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Routing/Router.php:710
#30 Illuminate\Routing\Router:runRouteWithinStack in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Routing/Router.php:675
#29 Illuminate\Routing\Router:dispatchToRoute in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Routing/Router.php:635
#28 Illuminate\Routing\Router:dispatch in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:236
#27 Illuminate\Foundation\Http\Kernel:Illuminate\Foundation\Http\{closure} in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139
#26 call_user_func in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:139
#25 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/eo-wallet/vendor/barryvdh/laravel-debugbar/src/Middleware/Debugbar.php:49
#24 Barryvdh\Debugbar\Middleware\Debugbar:handle in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#23 call_user_func_array in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#22 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php:50
#21 Illuminate\Foundation\Http\Middleware\VerifyCsrfToken:handle in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#20 call_user_func_array in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#19 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php:49
#18 Illuminate\View\Middleware\ShareErrorsFromSession:handle in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#17 call_user_func_array in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#16 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php:62
#15 Illuminate\Session\Middleware\StartSession:handle in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#14 call_user_func_array in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#13 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php:37
#12 Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse:handle in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#11 call_user_func_array in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#10 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php:59
#9 Illuminate\Cookie\Middleware\EncryptCookies:handle in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#8 call_user_func_array in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#7 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php:44
#6 Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode:handle in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#5 call_user_func_array in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:124
#4 Illuminate\Pipeline\Pipeline:Illuminate\Pipeline\{closure} in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
#3 call_user_func in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php:103
#2 Illuminate\Pipeline\Pipeline:then in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:122
#1 Illuminate\Foundation\Http\Kernel:sendRequestThroughRouter in /var/www/html/eo-wallet/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php:87
#0 Illuminate\Foundation\Http\Kernel:handle in /var/www/html/eo-wallet/public/index.php:54

Do you have any clues on how to make this work?

Thanks.

**Comment by freekmurze** [comment]
I'm thinking you forgot to import a namespace. Please post the code where you try to log something.

**Comment by pongz79** [comment]
```php
<?php

namespace App\Http\Models\v1;


use App\Http\Controllers\v1\RequestController;
use App\Http\Middleware\v1\WalletUserAuth;
use App\Http\Models\v1\ApiClient;
use Illuminate\Http\Request;
use Spatie\Activitylog\Models\Activity;

class Balance
{
    public function getBalance(Request $request)
    {
        Activity::log('User called get balance', 2153306);
    }
}
```

**Comment by freekmurze** [comment]
It's what I suspected. You've imported the model instead of the facade.

Change `use Spatie\Activitylog\Models\Activity` to `use Activity` to make it work.

**Comment by pongz79** [comment]
Awesome.
Thanks for the help.

**Comment by freekmurze** [comment]
I'll add a hint in the readme so future users won't stumble.
