### ISSUE TITLE
[Proposal] How about replacing varchar with text/json?

### ISSUE THREAD

**Issue by themsaid** [spatie/activitylog#33]
This package is perfect for logging actions with simple messages "Jack updated Post id:123.", but when it comes to logging complex actions with deep details I believe having the field as `text/json` and allow logging actions in a json format would make it more flexible.

```php
Activity::log([
    'action' => 'update',
    'updates' => [
        ['name' => ['old name', 'new name'],
        ['price' => [36, 78]]    
    ]
]);
```

This will allow logging actions in more detail, and also can be handy when logging messages in a multilingual application.

**Comment by freekmurze** [comment]
This is a good feature that I'll keep in mind where developing the next major version of the package. ETA: somewhere this year (yeah, so many others things to do first :-))
