### ISSUE TITLE
Vendor publish always creates migration

### ISSUE THREAD

**Issue by BojanKogoj** [spatie/activitylog#34]
Whenever I use `php artisan vendor:publish` it creates a new migration, even if an existing already exists. Did I do something wrong or a bug?

Only happens for this package

**Comment by freekmurze** [comment]
Yea, it's a bug. I'll fix it when a have some time. If you need this fix quick, I'd accept a PR.

**Comment by freekmurze** [comment]
This issue is fixed by @themsaid in v2.4.2

**Comment by BojanKogoj** [comment]
Thank you!
