### ISSUE TITLE
Add an artisan command to clear the database table

### ISSUE THREAD

**Issue by LukasMa** [spatie/activitylog#36]
Hi,
this is a Feature request. 
I think it's useful to have a command to clear the database table, basically doing what `Activity::cleanLog();` already does. This would be useful to clear the database table in develeopment environments or scripts.
I'm not used to package creation, so it might take some time to step through that and submit a PR.

Feel free to close this issue if you don't support that idea.

**Comment by freekmurze** [comment]
I think that best option is to add it as an artisan command in your own app.

We are currently preparing a new major version of the activity log package. Cleaning the table will probably come right of the box in that version.
