### ISSUE TITLE
Class 'CreateActivityLogTable' not found 

### ISSUE THREAD

**Issue by Mylo-92** [spatie/activitylog#38]
Good Day,

Every time I run ```php artisan migrate:refresh``` I get the following exception : **[Symfony\Component\Debug\Exception\FatalErrorException]  Class 'CreateActivityLogTable' not found**

How do I go about rectifying this error? Currently I am circumventing it by manually deleting my database and doing fresh migrations and seeds.

Regards,

**Comment by sebastiandedeyne** [comment]
Does the class exist in `database/migrations`? And could you run `composer dump-autoload` and try again?

**Comment by Mylo-92** [comment]
@sebastiandedeyne Yes the class exists, composer dump-autoload fixed it. Thank you for your time.
