### ISSUE TITLE
Model events trait not working in Laravel 5.2 

### ISSUE THREAD

**Issue by screenager** [spatie/activitylog#41]
Is it possible that when using the trait LogsActivity in your model, and implementing the corresponding interface, the model isn't yet subscribed to the model events?

**Comment by freekmurze** [comment]
[This function](https://github.com/spatie/activitylog/blob/master/src/Spatie/Activitylog/LogsActivity.php#L9) will be executed automatically by Laravel. It will ensure that the model is subscribed to the event with names returned by `getRecordActivityEvents`.
