### ISSUE TITLE
Logging activity to a different database

### ISSUE THREAD

**Issue by grafikkaos** [spatie/activitylog#42]
Hi,

Just have to say that this is a great package.  I would however live to log activities to another database rather.  Is there a way I can achieve this?

Thanks

**Comment by freekmurze** [comment]
It seems that it is possible to specify a db connection for each eloquent model: http://stackoverflow.com/questions/31847054/how-to-use-multiple-database-in-laravel

Haven't played around with this feature, so no guaranties on a painless solution.
