### ISSUE TITLE
Fetching a specific user logs ??

### ISSUE THREAD

**Issue by mikimaine** [spatie/activitylog#45]
Hi, thanks for this grate package.

my question is how can i retrieve activity logs for the currently logged in user only.

should i just create a new model and repository for the table activity_log and work the old way or is there a way in your package to get logs of `Auth::user().`

And also related question for removing all logs from the database because  this 
`Activity::cleanLog(); `
is not removing them should i go with my own repository solution ?

Thanks!

**Comment by freekmurze** [comment]
The package provides a `Spatie\Activitylog\Models\Activity` model. This class [is just another Eloquent model](https://github.com/spatie/activitylog/blob/master/src/Spatie/Activitylog/Models/Activity.php#L9) so you can perform `where`'s and `delete`'s on it like there's no tomorrow.
